### ISSUE TITLE
Hogwarts Legacy

### ISSUE THREAD

**Issue by lmachens** [REDxEYE/UTextureDecoder#2]
Hi,
thx for this tool!
I tried to decode Hogwarts Legacy textures (UE 4.27), but failed:

```
C:\dev\umodel\UmodelSaved\Game\UI\HUD\MiniMap\MiniMapTiles\Overland\UI_T_IMGUIMap.uasset
Traceback (most recent call last):
  File "C:\dev\UTextureDecoder\runner.py", line 12, in <module>
    asset = UEAsset.from_buffer(asset_file)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\UTextureDecoder\asset.py", line 121, in from_buffer
    assert buffer.read_uint32() == 0x9E2A83C1
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

I used UModel to save folder packages.

Do you have an idea what could be the issue?

**Comment by REDxEYE** [comment]
Hello, can you please upload this asset?

**Comment by REDxEYE** [comment]
From what i see, it's magic ident is different

**Comment by lmachens** [comment]
https://we.tl/t-Y6nGDuFpPC
(it's over 25mb, can't upload it on GitHub)

**Comment by REDxEYE** [comment]
Was there a .uexp file?

**Comment by REDxEYE** [comment]
UE4.27 asset format is quite different from 4.26. I would need time to learn about it

**Comment by REDxEYE** [comment]
What version of Umodel have you used?
I cannot find how to read this package version in UModel source code. From what i found it should fail

**Comment by lmachens** [comment]
ACL 2.1 build:
https://www.gildor.org/smf/index.php/topic,8304.msg42970.html#msg42970
DL:
https://drive.google.com/file/d/1oJkC-1i1_pfI-h7pbX3hnOZM6qwK5JnO/view

There was no .uexp file.

**Comment by REDxEYE** [comment]
I see, but i need it's source code

**Comment by lmachens** [comment]
Sorry, don't have it.

**Comment by REDxEYE** [comment]
I'm asking because official version of UModel has no support for Hogwarts legacy asset format

**Comment by lmachens** [comment]
Maybe ask in the forum if the code for that build is available?
