### ISSUE TITLE
Hello Neighbor 2 (Hello Copter)

### ISSUE THREAD

**Issue by Zaurzo** [REDxEYE/UTextureDecoder#3]
I stumbled upon this tool and tried it out because of these textures I've been trying to get, but as fate has it, it doesn't seem to work. I don't know anything about python so I'll let you have a look at it

```
D:\Game Content\HelloNeighbor2\Content\Extract\HelloNeighbor2\Plugins\HN2DLC\Content\Materials\drone\T_Drone_Diff.uasset
Traceback (most recent call last):
  File "C:\Users\NCG\Downloads\Compressed\UTextureDecoder-master\UTextureDecoder-master\runner.py", line 23, in <module>
    obj = Texture2D.from_buffer(uexp_file, asset.name_map, asset.imported_objects, asset.export_size)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NCG\Downloads\Compressed\UTextureDecoder-master\UTextureDecoder-master\texture_2d.py", line 361, in from_buffer
    pixel_format = read_name(buffer, name_map)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NCG\Downloads\Compressed\UTextureDecoder-master\UTextureDecoder-master\asset.py", line 25, in read_name
    name = name_map[name_index].value + (f"_{name_number}" if name_number > 0 else "")
           ~~~~~~~~^^^^^^^^^^^^
IndexError: list index out of range
```

**Comment by REDxEYE** [comment]
What UE version is this game using?

**Comment by Zaurzo** [comment]
> What UE version is this game using?

4.27.2.0

**Comment by REDxEYE** [comment]
Ye, 27 changed how assets are stored and i haven't found enough "readable" docs to parse them

**Comment by Zaurzo** [comment]
Ah okay, thanks. Please lmk if you ever are able to parse these
