### ISSUE TITLE
4.27 VirtualTextures?

### ISSUE THREAD

**Issue by RobotSpark** [REDxEYE/UTextureDecoder#4]
Hi, I was curious if the issues with decoding virtual textures from 4.27 Unreal Engine games has been solved yet, or if this is possible to implement - I have been trying to get virtual textures from Post Scriptum to work, and I feel so close yet so far. If it helps, this is the error message I run into when trying to decode a texture (the directory the files are located in has been replaced with [DIRECTORY] for privacy):
```
Traceback (most recent call last):
  File "[DIRECTORY]\UTextureDecoder-master\UTextureDecoder-master\runner.py", line 23, in <module>
    obj = Texture2D.from_buffer(uexp_file, asset.name_map, asset.imported_objects, asset.export_size)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[DIRECTORY]\UTextureDecoder-master\UTextureDecoder-master\texture_2d.py", line 361, in from_buffer
    pixel_format = read_name(buffer, name_map)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[DIRECTORY]\UTextureDecoder-master\UTextureDecoder-master\asset.py", line 25, in read_name
    name = name_map[name_index].value + (f"_{name_number}" if name_number > 0 else "")
           ~~~~~~~~^^^^^^^^^^^^
IndexError: list index out of range
```

**Comment by REDxEYE** [comment]
Issue with 4.27 is that I don't have info about .27 asset/VT-header structures.
